name: rocko
favicon: null
layout_spectrum: 0.1176
typography_spectrum: 0.10759
title: Rocko the Rottie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
